

	Custom_Hud[playerid][0] = CreatePlayerTextDraw(playerid, 532.999511, 50.466648, "custom_hud:progress"); // progress health
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][0], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][0], 55.000000, 5.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][0], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][0], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][0], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][0], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][0], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][0], 0);

	Custom_Hud[playerid][1] = CreatePlayerTextDraw(playerid, 532.999511, 50.466648, "ld_spac:white"); // progress health
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][1], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][1], 55.000000, 5.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][1], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][1], -435549441);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][1], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][1], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][1], 0);

	Custom_Hud[playerid][2] = CreatePlayerTextDraw(playerid, 604.333129, 33.874050, "weapon:fist"); // weapon
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][2], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][2], 28.000000, 30.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][2], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][2], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][2], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][2], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][2], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][2], 0);

	Custom_Hud[playerid][3] = CreatePlayerTextDraw(playerid, 532.999511, 41.340740, "custom_hud:progress"); // progress armour
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][3], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][3], 55.000000, 5.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][3], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][3], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][3], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][3], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][3], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][3], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][3], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][3], 0);

	Custom_Hud[playerid][4] = CreatePlayerTextDraw(playerid, 532.999511, 41.340740, "ld_spac:white"); // progress armour
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][4], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][4], 55.000000, 5.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][4], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][4], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][4], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][4], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][4], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][4], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][4], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][4], 0);

	Custom_Hud[playerid][5] = CreatePlayerTextDraw(playerid, 528.999145, 38.437042, "custom_hud:cursor");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][5], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][5], 6.000000, 11.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][5], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][5], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][5], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][5], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][5], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][5], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][5], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][5], 0);

	Custom_Hud[playerid][6] = CreatePlayerTextDraw(playerid, 528.999145, 47.562965, "custom_hud:cursor");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][6], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][6], 6.000000, 11.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][6], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][6], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][6], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][6], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][6], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][6], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][6], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][6], 0);

	Custom_Hud[playerid][7] = CreatePlayerTextDraw(playerid, 585.665771, 47.562965, "custom_hud:cursor");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][7], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][7], 6.000000, 11.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][7], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][7], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][7], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][7], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][7], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][7], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][7], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][7], 0);

	Custom_Hud[playerid][8] = CreatePlayerTextDraw(playerid, 585.665771, 38.437049, "custom_hud:cursor");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][8], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][8], 6.000000, 11.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][8], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][8], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][8], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][8], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][8], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][8], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][8], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][8], 0);

	Custom_Hud[playerid][9] = CreatePlayerTextDraw(playerid, 520.998962, 39.266677, "custom_hud:armour"); //icon armour
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][9], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][9], 8.000000, 8.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][9], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][9], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][9], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][9], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][9], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][9], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][9], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][9], 0);

	Custom_Hud[playerid][10] = CreatePlayerTextDraw(playerid, 520.665649, 49.637039, "custom_hud:health"); //icon health
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][10], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][10], 8.000000, 8.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][10], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][10], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][10], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][10], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][10], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][10], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][10], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][10], 0);

	Custom_Hud[playerid][11] = CreatePlayerTextDraw(playerid, 497.999145, 70.377769, "custom_hud:money");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][11], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][11], 90.000000, 18.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][11], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][11], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][11], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][11], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][11], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][11], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][11], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][11], 0);

	Custom_Hud[playerid][12] = CreatePlayerTextDraw(playerid, 525.333435, 71.777770, "99999999");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][12], 0.344999, 1.450666);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][12], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][12], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][12], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][12], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][12], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][12], 3);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][12], 1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][12], 0);

	Custom_Hud[playerid][13] = CreatePlayerTextDraw(playerid, 502.332916, 89.359237, "custom_hud:wanted"); //Wanted
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][13], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][13], 81.000000, 12.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][13], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][13], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][13], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][13], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][13], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][13], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][13], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][13], 0);

	Custom_Hud[playerid][14] = CreatePlayerTextDraw(playerid, 502.332916, 89.359230, "custom_hud:star"); //Star wanted 1
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][14], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][14], 9.000000, 12.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][14], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][14], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][14], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][14], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][14], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][14], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][14], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][14], 0);

	Custom_Hud[playerid][15] = CreatePlayerTextDraw(playerid, 516.332946, 89.359230, "custom_hud:star"); //Star wanted 2
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][15], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][15], 9.000000, 12.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][15], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][15], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][15], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][15], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][15], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][15], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][15], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][15], 0);

	Custom_Hud[playerid][16] = CreatePlayerTextDraw(playerid, 530.999511, 89.359230, "custom_hud:star"); //Star wanted 3
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][16], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][16], 9.000000, 12.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][16], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][16], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][16], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][16], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][16], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][16], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][16], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][16], 0);

	Custom_Hud[playerid][17] = CreatePlayerTextDraw(playerid, 544.999511, 89.774055, "custom_hud:star"); //Star wanted 4
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][17], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][17], 9.000000, 12.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][17], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][17], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][17], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][17], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][17], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][17], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][17], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][17], 0);

	Custom_Hud[playerid][18] = CreatePlayerTextDraw(playerid, 559.332824, 89.359230, "custom_hud:star"); //Star wanted 5
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][18], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][18], 9.000000, 12.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][18], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][18], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][18], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][18], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][18], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][18], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][18], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][18], 0);

	Custom_Hud[playerid][19] = CreatePlayerTextDraw(playerid, 573.666015, 89.359222, "custom_hud:star"); //Star wanted 6
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][19], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][19], 9.000000, 12.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][19], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][19], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][19], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][19], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][19], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][19], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][19], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][19], 0);

	Custom_Hud[playerid][20] = CreatePlayerTextDraw(playerid, 532.999633, 30.140745, "custom_hud:progress");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][20], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][20], 55.000000, 5.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][20], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][20], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][20], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][20], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][20], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][20], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][20], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][20], 0);

	Custom_Hud[playerid][21] = CreatePlayerTextDraw(playerid, 531.666320, 30.140745, "ld_spac:white");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][21], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][21], 55.000000, 5.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][21], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][21], -89911297);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][21], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][21], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][21], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][21], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][21], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][21], 0);

	Custom_Hud[playerid][22] = CreatePlayerTextDraw(playerid, 528.999145, 26.822242, "custom_hud:cursor");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][22], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][22], 6.000000, 11.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][22], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][22], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][22], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][22], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][22], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][22], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][22], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][22], 0);

	Custom_Hud[playerid][23] = CreatePlayerTextDraw(playerid, 585.332214, 26.822244, "custom_hud:cursor");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][23], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][23], 6.000000, 11.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][23], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][23], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][23], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][23], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][23], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][23], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][23], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][23], 0);

	Custom_Hud[playerid][24] = CreatePlayerTextDraw(playerid, 532.333129, 20.185203, "custom_hud:progress");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][24], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][24], 55.000000, 5.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][24], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][24], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][24], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][24], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][24], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][24], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][24], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][24], 0);

	Custom_Hud[playerid][25] = CreatePlayerTextDraw(playerid, 531.666381, 20.185203, "ld_spac:white");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][25], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][25], 55.000000, 5.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][25], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][25], 1273494527);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][25], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][25], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][25], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][25], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][25], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][25], 0);

	Custom_Hud[playerid][26] = CreatePlayerTextDraw(playerid, 585.332153, 16.866706, "custom_hud:cursor");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][26], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][26], 6.000000, 11.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][26], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][26], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][26], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][26], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][26], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][26], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][26], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][26], 0);

	Custom_Hud[playerid][27] = CreatePlayerTextDraw(playerid, 528.998657, 17.281511, "custom_hud:cursor");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][27], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][27], 6.000000, 11.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][27], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][27], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][27], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][27], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][27], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][27], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][27], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][27], 0);

	Custom_Hud[playerid][28] = CreatePlayerTextDraw(playerid, 520.665710, 27.651866, "custom_hud:eat");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][28], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][28], 8.000000, 8.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][28], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][28], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][28], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][28], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][28], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][28], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][28], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][28], 0);

	Custom_Hud[playerid][29] = CreatePlayerTextDraw(playerid, 520.332336, 17.696310, "custom_hud:eat");
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][29], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, Custom_Hud[playerid][29], 8.000000, 8.000000);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][29], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][29], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][29], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][29], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][29], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][29], 4);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][29], 0);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][29], 0);

	Custom_Hud[playerid][30] = CreatePlayerTextDraw(playerid, 606.999938, 58.503715, "100"); //so luong dan
	PlayerTextDrawLetterSize(playerid, Custom_Hud[playerid][30], 0.254999, 1.139554);
	PlayerTextDrawAlignment(playerid, Custom_Hud[playerid][30], 1);
	PlayerTextDrawColor(playerid, Custom_Hud[playerid][30], -1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][30], 0);
	PlayerTextDrawSetOutline(playerid, Custom_Hud[playerid][30], 0);
	PlayerTextDrawBackgroundColor(playerid, Custom_Hud[playerid][30], 255);
	PlayerTextDrawFont(playerid, Custom_Hud[playerid][30], 3);
	PlayerTextDrawSetProportional(playerid, Custom_Hud[playerid][30], 1);
	PlayerTextDrawSetShadow(playerid, Custom_Hud[playerid][30], 0);

	//Loading Textdraw
	Loading_Text[playerid][0] = CreatePlayerTextDraw(playerid, 262.666748, 333.940704, "box");
	PlayerTextDrawLetterSize(playerid, Loading_Text[playerid][0], 0.000000, 1.600000);
	PlayerTextDrawTextSize(playerid, Loading_Text[playerid][0], 369.000000, 0.000000);
	PlayerTextDrawAlignment(playerid, Loading_Text[playerid][0], 1);
	PlayerTextDrawColor(playerid, Loading_Text[playerid][0], -1);
	PlayerTextDrawUseBox(playerid, Loading_Text[playerid][0], 1);
	PlayerTextDrawBoxColor(playerid, Loading_Text[playerid][0], 606348466);
	PlayerTextDrawSetShadow(playerid, Loading_Text[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid, Loading_Text[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid, Loading_Text[playerid][0], 255);
	PlayerTextDrawFont(playerid, Loading_Text[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, Loading_Text[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, Loading_Text[playerid][0], 0);

	Loading_Text[playerid][1] = CreatePlayerTextDraw(playerid, 262.666748, 333.940704, "box");
	PlayerTextDrawLetterSize(playerid, Loading_Text[playerid][1], 0.000000, 1.566667);
	PlayerTextDrawTextSize(playerid, Loading_Text[playerid][1], 369.000000, 0.000000);
	PlayerTextDrawAlignment(playerid, Loading_Text[playerid][1], 1);
	PlayerTextDrawColor(playerid, Loading_Text[playerid][1], -1);
	PlayerTextDrawUseBox(playerid, Loading_Text[playerid][1], 1);
	PlayerTextDrawBoxColor(playerid, Loading_Text[playerid][1], -15066369);
	PlayerTextDrawSetShadow(playerid, Loading_Text[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid, Loading_Text[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid, Loading_Text[playerid][1], 255);
	PlayerTextDrawFont(playerid, Loading_Text[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, Loading_Text[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, Loading_Text[playerid][1], 0);

	Loading_Text[playerid][2] = CreatePlayerTextDraw(playerid, 294.666778, 335.185241, "Dang_hai...");
	PlayerTextDrawLetterSize(playerid, Loading_Text[playerid][2], 0.254000, 1.189333);
	PlayerTextDrawAlignment(playerid, Loading_Text[playerid][2], 1);
	PlayerTextDrawColor(playerid, Loading_Text[playerid][2], -1);
	PlayerTextDrawSetShadow(playerid, Loading_Text[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid, Loading_Text[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid, Loading_Text[playerid][2], 255);
	PlayerTextDrawFont(playerid, Loading_Text[playerid][2], 3);
	PlayerTextDrawSetProportional(playerid, Loading_Text[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, Loading_Text[playerid][2], 0);


	//Admin

	SpecPlayer[playerid][0] = CreatePlayerTextDraw(playerid, 511.666687, 244.340805, "box");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][0], 0.000000, 22.866662);
	PlayerTextDrawTextSize(playerid, SpecPlayer[playerid][0], 648.000000, 0.000000);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][0], 1);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][0], -1);
	PlayerTextDrawUseBox(playerid, SpecPlayer[playerid][0], 1);
	PlayerTextDrawBoxColor(playerid, SpecPlayer[playerid][0], 606348543);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][0], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][0], 0);

	SpecPlayer[playerid][1] = CreatePlayerTextDraw(playerid, 514.666809, 247.244506, "box");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][1], 0.000000, 21.900005);
	PlayerTextDrawTextSize(playerid, SpecPlayer[playerid][1], 637.000000, 0.000000);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][1], 1);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][1], -1);
	PlayerTextDrawUseBox(playerid, SpecPlayer[playerid][1], 1);
	PlayerTextDrawBoxColor(playerid, SpecPlayer[playerid][1], -433246722);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][1], 690553089);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][1], 0);

	SpecPlayer[playerid][2] = CreatePlayerTextDraw(playerid, 516.000000, 246.414840, "Ten:_Brian_Nelson");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][2], 0.292000, 1.629036);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][2], 1);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][2], -1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][2], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][2], 0);

	SpecPlayer[playerid][3] = CreatePlayerTextDraw(playerid, 516.666625, 263.007568, "Cap_do:_200");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][3], 0.292000, 1.629036);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][3], 1);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][3], -1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][3], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][3], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][3], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][3], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][3], 0);

	SpecPlayer[playerid][4] = CreatePlayerTextDraw(playerid, 517.333251, 280.015014, "Vi_tri:_Los_Santos");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][4], 0.292000, 1.629036);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][4], 1);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][4], -1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][4], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][4], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][4], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][4], 0);

	SpecPlayer[playerid][5] = CreatePlayerTextDraw(playerid, 518.000000, 297.022491, "Tien:_500000");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][5], 0.292000, 1.629036);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][5], 1);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][5], -1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][5], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][5], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][5], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][5], 0);

	SpecPlayer[playerid][6] = CreatePlayerTextDraw(playerid, 518.333312, 313.615112, "Bank:_500000");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][6], 0.292000, 1.629036);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][6], 1);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][6], -1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][6], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][6], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][6], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][6], 0);

	SpecPlayer[playerid][7] = CreatePlayerTextDraw(playerid, 518.666809, 331.452239, "Paycheck:_60000");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][7], 0.292000, 1.629036);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][7], 1);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][7], -1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][7], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][7], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][7], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][7], 0);

	SpecPlayer[playerid][8] = CreatePlayerTextDraw(playerid, 575.000122, 428.933471, "Stop");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][8], 0.532333, 1.815703);
	PlayerTextDrawTextSize(playerid, SpecPlayer[playerid][8], 0.000000, 58.000000);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][8], 2);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][8], -1);
	PlayerTextDrawUseBox(playerid, SpecPlayer[playerid][8], 1);
	PlayerTextDrawBoxColor(playerid, SpecPlayer[playerid][8], 522133503);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][8], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][8], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][8], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][8], 0);
	PlayerTextDrawSetSelectable(playerid, SpecPlayer[playerid][8], 1);

	SpecPlayer[playerid][9] = CreatePlayerTextDraw(playerid, 575.000122, 401.555480, "Kick");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][9], 0.532333, 1.815703);
	PlayerTextDrawTextSize(playerid, SpecPlayer[playerid][9], 0.000000, 58.000000);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][9], 2);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][9], -1);
	PlayerTextDrawUseBox(playerid, SpecPlayer[playerid][9], 1);
	PlayerTextDrawBoxColor(playerid, SpecPlayer[playerid][9], 522133503);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][9], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][9], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][9], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][9], 0);
	PlayerTextDrawSetSelectable(playerid, SpecPlayer[playerid][9], 1);

	SpecPlayer[playerid][10] = CreatePlayerTextDraw(playerid, 575.000183, 373.762786, "Banned");
	PlayerTextDrawLetterSize(playerid, SpecPlayer[playerid][10], 0.532333, 1.815703);
	PlayerTextDrawTextSize(playerid, SpecPlayer[playerid][10], 0.000000, 58.000000);
	PlayerTextDrawAlignment(playerid, SpecPlayer[playerid][10], 2);
	PlayerTextDrawColor(playerid, SpecPlayer[playerid][10], -1);
	PlayerTextDrawUseBox(playerid, SpecPlayer[playerid][10], 1);
	PlayerTextDrawBoxColor(playerid, SpecPlayer[playerid][10], 522133503);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][10], 0);
	PlayerTextDrawSetOutline(playerid, SpecPlayer[playerid][10], 0);
	PlayerTextDrawBackgroundColor(playerid, SpecPlayer[playerid][10], 255);
	PlayerTextDrawFont(playerid, SpecPlayer[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, SpecPlayer[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, SpecPlayer[playerid][10], 0);
	PlayerTextDrawSetSelectable(playerid, SpecPlayer[playerid][10], 1);